import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getConpanyInformations } from "./crud";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const companyInformation = await getConpanyInformations();

export const metadata: Metadata = {
  title: companyInformation?.name?.english || "Default Title",
  description: "Generated by create next app",
  icons: {
    icon: companyInformation?.logo || "/default-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans?.variable} ${geistMono?.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
